import { StyleSheet, Dimensions } from 'react-native';

const { height: SCREEN_H } = Dimensions.get('window');

export const appStyles = StyleSheet.create({
  container: { flex: 1 },

  topPill: {
    position: 'absolute',
    top: 52,
    left: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    zIndex: 5
  },
  topPillText: { fontSize: 15, fontWeight: '600' },
  brandIcon: { width: 18, height: 18, borderRadius: 4 },
  glass: { overflow: 'hidden' },

  statusPill: {
    position: 'absolute',
    top: 52,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    zIndex: 6,
  },
  gearIcon: { fontSize: 15, fontWeight: '900', transform: [{ scale: 1.5 }] },
  statusText: { fontSize: 13, fontWeight: '700' },

  radiusDockWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 140,
    alignItems: 'center',
    zIndex: 6,
  },
  radiusDock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 14,
    shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 10, shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  dockBtn: { backgroundColor: '#0F172A', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10 },
  dockBtnTxt: { color: '#fff', fontSize: 12, fontWeight: '800' },
  dockRadius: { minWidth: 84, textAlign: 'center', fontSize: 14, fontWeight: '800' },
  dockAction: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 10 },
  dockActionTxt: { color: '#fff', fontSize: 13, fontWeight: '800' },
  dockCircle: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: '#111' },
  dockCircleTxt: { color: '#fff', fontSize: 16, fontWeight: '900' },

  meContainer: { width: 50, height: 50, alignItems: 'center', justifyContent: 'center' },
  pulseRing: { position: 'absolute', width: 50, height: 50, borderRadius: 25, backgroundColor: 'rgba(56,116,255,0.25)' },
  meDotShadow: { width: 20, height: 20, borderRadius: 10, backgroundColor: '#3874FF', borderWidth: 3, borderColor: '#fff', shadowColor: '#3874FF', shadowOpacity: 0.7, shadowRadius: 10, shadowOffset: { width: 0, height: 0 } },
  meDot: { flex: 1, borderRadius: 10 },

  crosshair: { position: 'absolute', left: '50%', top: '50%', marginLeft: -4, marginTop: -4, width: 8, height: 8, borderRadius: 4, borderWidth: 1.5, borderColor: '#111', backgroundColor: 'rgba(255,255,255,0.95)' },
  crossDot: { flex: 1, borderRadius: 6 },

  sheet: {
    position: 'absolute',
    left: 0, right: 0, bottom: 0,
    borderTopLeftRadius: 18, borderTopRightRadius: 18,
    shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 12, shadowOffset: { width: 0, height: -4 },
    elevation: 10,
    zIndex: 7,
  },
  sheetHandleArea: { alignItems: 'center', paddingTop: 10, paddingBottom: 4 },
  handle: { width: 44, height: 5, borderRadius: 3 },
  sheetHeader: { paddingHorizontal: 16, paddingVertical: 10 },
  sheetTitle: { fontSize: 18, fontWeight: '800' },
  sheetSubtitle: { fontSize: 13, opacity: 0.6, marginTop: 2 },
  filterRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, marginTop: 2 },
  filterBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999 },
  filterTxt: { fontSize: 12, fontWeight: '800' },
  sheetBody: { flex: 1, paddingHorizontal: 16, paddingVertical: 8 },
  placeholder: { fontSize: 14 },

  // ---- List cards ----
  card: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    paddingRight: 96, // rezerva pro pravý navigační pill v overlayi
    borderRadius: 14,
    marginBottom: 8,
  },
  cardTitle: { fontSize: 15, fontWeight: '800' },
  cardSub: { marginTop: 4, fontSize: 12 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4 },
  cardMeta: { fontSize: 11, fontWeight: '800' },

  badgeRow: { flexDirection: 'row', gap: 6, marginTop: 6 },
  badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999 },
  badgeTxt: { fontSize: 11, fontWeight: '800' },

  favBtn: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  favIcon: { color: '#A3AEC2', fontSize: 18, fontWeight: '900' },
  // Aktivní hvězda výrazně žlutá (s ohledem na dark/light)
  favIconActive: { color: '#FACC15' },

  openBadge: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  openDot: { width: 8, height: 8, borderRadius: 4 },

  navRow: { position: 'absolute', right: 12, bottom: 8, flexDirection: 'row', gap: 6 },
  navBtn: { backgroundColor: '#111', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 },
  navTxt: { color: '#fff', fontSize: 11, fontWeight: '900' },
  navBigBtn: { backgroundColor: '#111', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12 },
  navBigTxt: { color: '#fff', fontSize: 13, fontWeight: '900' },
  navMoreBtn: { backgroundColor: '#111', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 12 },
  navMoreTxt: { color: '#fff', fontSize: 18, fontWeight: '900', lineHeight: 18 },

  clusterWrap: { minWidth: 40, height: 40, paddingHorizontal: 8, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: '#111', borderWidth: 3, borderColor: '#fff', shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 7, shadowOffset: { width: 0, height: 3 } },
  clusterText: { color: '#fff', fontSize: 14, fontWeight: '900' },

  quickChipsWrap: { position: 'absolute', right: 10, top: SCREEN_H * 0.28, gap: 8, zIndex: 6, alignItems: 'flex-end' },
  quickChip: { backgroundColor: '#0F172A', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 12 },
  quickChipActive: { backgroundColor: '#111' },
  quickChipTxt: { color: '#fff', fontSize: 12, fontWeight: '800' },
  quickChipTxtActive: { textDecorationLine: 'underline' },

  // Pin styles
  pinWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinGlow: {
    position: 'absolute',
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 4,
    opacity: 0.55,
  },
  pinTop: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2.5,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  pinStem: {
    width: 0,
    height: 0,
    borderLeftWidth: 7,
    borderRightWidth: 7,
    borderTopWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    marginTop: -3,
  },
  pinFav: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FFD700',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#fff',
  },
  pinFavTxt: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
